# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewBudget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewBudget
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.6'

  target 'NewBudgetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewBudgetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
